language: ruby
branches:
  only:
  - master
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
- 2.1.10
- 2.2.5
- 2.3.1
- 2.4.0
- jruby
- rbx-2
matrix:
  allow_failures:
  - rvm: 1.8.7
  - rvm: rbx-2
  - rvm: jruby
  - rvm: 2.4.0
cache: bundler
env:
  global:
  - secure: OFKp0J81VrKXfpQZWkwSfsG/knN4tr45yDAGekFy4FKcA6Ra6EqDUzcY1MVrkKq9YRUgLJRfjgqF3Ei0cm2qMo1dy5XUG/fY8upTVdQK2Nm1qfbjnh70+vnYpHidHg9pEI8QROwsM7n19QoT16j1af4UinGFE/HBiJpuXcABuLw=
  - secure: Jkc/DnS1knCf0fO3qUxaExoEPEEuTFcmJGP/DkOZ5tnMSro8pjgzXIIzMaQSoRO4B7Hv0o7NzNTqNV6/KgB3jLlsj4dQtjkTnZ21Uk0sah5wZpWyC6QhtuIv1yA2utIsNLygU9WDoyD+V9EwuYrLNone1zSGIclAjlPO4xCYo6E=
  - secure: azXyWh9pmK8NS5bKnM4iA2HeJxHjB+fERNQOnQAKEYPF5fWi10+wj6BBZ6wVI0z/J812TfeW+EwLFphAUxZNnFpt5mfE2u9W5AIurdmJrzBE/Q5ousZNF+Vc6mCCCJzsYtFq0QB7APP0vlR7LRytv+aYJ9mgnEW2PIGhbKtZ+1M= # ALGOLIA_APP_ID
